src/app/erp/MyCompanyName.Erp.Web/Components/Logo/MainLogoViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Volo.Abp.AspNetCore.Mvc;

namespace MyCompanyName.Erp.Web.Components
{
    public class MainLogoViewComponent : AbpViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View("~/Components/Logo/Default.cshtml");
        }
    }
}

src/app/erp/MyCompanyName.Erp.Web/Components/Menu/SiderMenuViewComponent.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Volo.Abp.AspNetCore.Mvc;
using Volo.Abp.UI.Navigation;

namespace MyCompanyName.Erp.Web.Components
{
    public class SiderMenuViewComponent : AbpViewComponent
    {
        private readonly IMenuManager _menuManager;

        public SiderMenuViewComponent(IMenuManager menuManager)
        {
            _menuManager = menuManager;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var menu = await _menuManager.GetAsync(StandardMenus.Main); 
            return View("~/Components/Menu/Default.cshtml", menu);
        }
    }
}

src/app/erp/MyCompanyName.Erp.Web/Pages/Home.cshtml.cs
using MyCompanyName.Web.Shared.Pages;

namespace MyCompanyName.Erp.Web.Pages
{
    public class HomeModel : BasePageModel
    {
        public void OnGet()
        {
        }
    }
}

src/app/erp/MyCompanyName.Erp.Web/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Logging;
using MyCompanyName.Web.Shared.Pages;
using Volo.Abp;

namespace MyCompanyName.Erp.Web.Pages
{
    [Authorize]
    public class IndexModel : BasePageModel
    {
        public void OnGet()
        {
            if (!CurrentTenant.IsAvailable)
            {
                throw new UserFriendlyException(L["LoginSystemIsNotAllowed"]);
            }
        }
    }
}

src/app/erp/MyCompanyName.Erp.Web/Pages/Home.cshtml
@page
@model HomeModel
@inject IStringLocalizer<ErpResource> L
@{
}
<a-app id="homePage">
    <a-back-top></a-back-top>
    <a-affix>
        <a-alert banner closable>
            <template #icon>
                <i class="fa fa-volume-up"></i>
            </template>
            <template #message>
                <span style="white-space: nowrap;color:var(--highlight-color)">
                    <marquee onmouseover="this.stop()" onmouseout="this.start()" style="height:19px;margin-bottom:-3px">
                        公告条测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试
                    </marquee>
                </span>
            </template>
        </a-alert>
    </a-affix>
    <a-row :gutter="[8,8]" style="margin:4px">
        <a-col :xs="24" :md="12" :lg="8" :xl="6" :xxl="4">
            <a-card :loading="appUpdate.loading" title="通知消息">
                <a-timeline>
                    <template v-for="(item,index) in appUpdate.items">
                        <a-timeline-item>
                            <template #dot v-if="index==appUpdate.items.length-1">
                                <i class="fa fa-clock-o" style="font-size: 16px"></i>
                            </template>
                            {{item.time}} {{item.title}}
                        </a-timeline-item>
                    </template>
                </a-timeline>
            </a-card>
        </a-col>
        <a-col :xs="24" :md="12" :lg="8" :xl="6" :xxl="4">
            <a-card :loading="appUpdate.loading" :title="appUpdate.title">
                <a-timeline>
                    <template v-for="(item,index) in appUpdate.items">
                        <a-timeline-item>
                            <template #dot v-if="index==appUpdate.items.length-1">
                                <i class="fa fa-clock-o" style="font-size: 16px"></i>
                            </template>
                            {{item.time}} {{item.title}}
                        </a-timeline-item>
                    </template>
                </a-timeline>
            </a-card>
        </a-col>
    </a-row>
</a-app>

@section Scripts {
    <a-script src="/Pages/Home.cshtml.js" />
}

src/app/erp/MyCompanyName.Erp.Web/Pages/Index.cshtml
@page
@model IndexModel
@inject IStringLocalizer<ErpResource> L
@{
    ViewData["PageType"] = "layout";
}
<a-app id="adminLayout">
    <a-layout hasSider>
        <vc:sider-menu />
        <a-layout>
            <a-layout-header>
                <a-row v-bind="{justify:'start',align:'middle'}">
                    <a-col>
                        <vc:main-logo />
                    </a-col>
                    <a-col flex="auto">

                    </a-col>
                    <a-col flex="0 0 auto">
                        <div style="margin-right: 8px;padding-top:4px">
                            <vc:language-switch />
                        </div>
                    </a-col>
                    <a-col flex="0 0 auto">
                        <vc:user-menu />
                    </a-col>
                </a-row>
            </a-layout-header>
            <a-layout-content>
                <div id="menuTab">
                    <a-tabs v-model:active-key="activeKey" size="small" hide-add type="editable-card" v-on:edit="OnEdit">
                        <a-tab-pane v-for="pane in panes" :key="pane.key" :closable="pane.closable">
                            <template #tab>
                                <a-dropdown :trigger="['contextmenu']">
                                    <span>
                                        <i v-if="pane.icon" :class="pane.icon"></i>
                                        {{pane.title}}
                                    </span>
                                    <template #overlay>
                                        <a-menu style="min-width:120px">
                                            <template v-for="(menu,index) in  pane.contextmenu||[]">
                                                <a-menu-item :key="index" v-if="menu.type!=='divider'" v-on:click="menu.OnClick">
                                                    <i v-if="menu.icon" :class="menu.icon"></i>   {{menu.title}}
                                                </a-menu-item>
                                                <a-menu-divider v-else />
                                            </template>
                                        </a-menu>
                                    </template>
                                </a-dropdown>
                            </template>
                            <a-spin :spinning="pane.loading" tip="@L["LoadingWithThreeDot"]">
                                <iframe frameborder="0"
                                        allowtransparency="true"
                                        :src="pane.src"
                                        v-if="pane.render"
                                        v-on:load="pane.loading=false">
                                </iframe>
                            </a-spin>
                        </a-tab-pane>
                    </a-tabs>
                </div>
            </a-layout-content>
        </a-layout>
    </a-layout>

    @*<a-layout hasSider>
        <vc:sider-menu />
        <a-layout-header>
            <a-row v-bind="{justify:'start',align:'middle'}">
                <a-col class="menu" title="@L["AllMenus"]">
                    <i class="fa fa-bars"></i>
                </a-col>
                <a-col>
                    <vc:main-logo />
                </a-col>
                <a-col flex="auto">

                </a-col>
                <a-col flex="0 0 auto">
                    <div style="margin-right: 8px;padding-top:4px">
                        <vc:language-switch />
                    </div>
                </a-col>
                <a-col flex="0 0 auto">
                    <vc:user-menu />
                </a-col>
            </a-row>
        </a-layout-header>
        <a-layout hasSider>
            <a-layout-content>
                <div id="menuTab">
                    <a-tabs v-model:active-key="activeKey" size="small" hide-add type="editable-card" v-on:edit="OnEdit">
                        <a-tab-pane v-for="pane in panes" :key="pane.key" :closable="pane.closable">
                            <template #tab>
                                <a-dropdown :trigger="['contextmenu']">
                                    <span>
                                        <i v-if="pane.icon" :class="pane.icon"></i>
                                        {{pane.title}}
                                    </span>
                                    <template #overlay>
                                        <a-menu style="min-width:120px">
                                            <template v-for="(menu,index) in  pane.contextmenu||[]">
                                                <a-menu-item :key="index" v-if="menu.type!=='divider'" v-on:click="menu.OnClick">
                                                    <i v-if="menu.icon" :class="menu.icon"></i>   {{menu.title}}
                                                </a-menu-item>
                                                <a-menu-divider v-else />
                                            </template>
                                        </a-menu>
                                    </template>
                                </a-dropdown>
                            </template>
                            <a-spin :spinning="pane.loading" tip="@L["LoadingWithThreeDot"]">
                                <iframe frameborder="0"
                                        allowtransparency="true"
                                        :src="pane.src"
                                        v-if="pane.render"
                                        v-on:load="pane.loading=false">
                                </iframe>
                            </a-spin>
                        </a-tab-pane>
                    </a-tabs>
                </div>
            </a-layout-content>
        </a-layout>
    </a-layout>*@
</a-app>
@section Styles {
    <a-style-bundle>
        <a-style type="@typeof(SiderMenuStyleContributor)" />
        <a-style src="/Pages/Index.cshtml.css" />
    </a-style-bundle>
}
@section Scripts {
    <a-script-bundle>
        <a-script type="@typeof(SiderMenuScriptContributor)" />
        <a-script src="/Pages/Index.cshtml.js" />
    </a-script-bundle>
}